### ISSUE TITLE
"package" is marked required, but is not present in examples

### ISSUE THREAD

**Issue by kjwilcox** [mdomke/concourse-devpi-resource#1]
I am attempting to use this resource in a concourse pipeline, and found the documentation to be a little confusing.

I am unsure whether or not the "package" key is actually required (otherwise I would submit a PR). If it is required, it would be nice to add it to the example.

Also, a more comprehensive example configuration (like a complete example build job) would be really helpful for a concourse beginner, though I think that request can be considered outside the scope of this issue.

Thanks for your time, and please let me know if there's anything I can do to help resolve this.

**Comment by mdomke** [comment]
The `package` parameter is actually required and it was missing in the example snippet. I updated the README accordingly.
